### ISSUE TITLE
How to broadcast message in room i have created??

### ISSUE THREAD

**Issue by nikunj1091** [walkor/phpsocket.io-for-win#1]
how can i  broadcast message to particular room??

$io->to("myroom")->emit('sendGroupMessage', $data);  not working??

Please help me as soon... thanks

**Comment by walkor** [comment]
$io->to("myroom")->emit('sendGroupMessage', $data); is the right way.
Not working?? Is there any error message?

**Comment by nikunj1091** [comment]
$socket->on('sendGroupMessage', function ($data)use($socket,$io){
        // we tell the client to execute 'new message';
        $io->in("myroom")->emit('sendGroupMessage', $data);
    });

i forget to use $io object  in use() that's why it tell undefiend variable $io,

it's working now fine ...

Thank you for your quick response!!!
